kind = "web"
previewPath = "/"
title = "Mintoria"
version = "1.0.0"
id = "artifacts/mintoria"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24783

[services.development]
run = "pnpm --filter @workspace/mintoria run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mintoria", "run", "build" ]
publicDir = "artifacts/mintoria/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24783"
BASE_PATH = "/"
